spring:
  application:
    name: cloudstorage

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qingyun_cloudstorage
    username: qingyun_mysql
    password: 0mLBsWnxmpmtOgBYxtV5

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: 20040919Zst-+
      database: 0

  servlet:
    multipart:
      max-file-size: 64GB
      max-request-size: 64GB

minio:
  endpoint: localhost
  port: 9000
  accessKey: 0mLBsWnxmpmtOgBYxtV5
  secretKey: 3ZewiA5znoWxNUKLbNHrLQKs7hjnyejkQPEsFSd9
  bucketName: qingyuncloudstorage

logging:
  level:
    root: info