package com.qingyun.cloudstorage.enumerate;

public class ResponseCode {
    public static final Integer SUCCESS = 200;
    public static final Integer ERROR = 500;
    public static final Integer INVALID_CREDENTIALS = 420;
    public static final Integer NOT_FOUND = 404;
    public static final Integer UNAUTHORIZED = 401;
    public static final Integer FORBIDDEN = 403;
    public static final Integer BAD_REQUEST = 400;
    public static final Integer METHOD_NOT_ALLOWED = 405;
    public static final Integer UNSUPPORTED_MEDIA_TYPE = 415;
    public static final Integer SERVICE_UNAVAILABLE = 503;
    public static final Integer GATEWAY_TIMEOUT = 504;
    public static final Integer HTTP_VERSION_NOT_SUPPORTED = 505;
    public static final Integer NETWORK_AUTHENTICATION_REQUIRED = 511;
    public static final Integer NOT_EXTENDED = 510;
    public static final Integer PRECONDITION_FAILED = 412;
    public static final Integer PAYLOAD_TOO_LARGE = 413;
    public static final Integer REQUEST_TIMEOUT = 408;
    public static final Integer TOO_MANY_REQUESTS = 429;
    public static final Integer LENGTH_REQUIRED = 411;
    public static final Integer CONFLICT = 409;
    public static final Integer GONE = 410;
    public static final Integer NOT_ACCEPTABLE = 406;
    public static final Integer REQUEST_ENTITY_TOO_LARGE = 413;
    public static final Integer REQUEST_URI_TOO_LONG = 414;
    public static final Integer REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    public static final Integer EXPECTATION_FAILED = 417;
    public static final Integer I_AM_A_TEAPOT = 418;
    public static final Integer MISDIRECTED_REQUEST = 421;
    public static final Integer UNPROCESSABLE_ENTITY = 422;
    public static final Integer LOCKED = 423;
    public static final Integer FAILED_DEPENDENCY = 424;
    public static final Integer UPGRADE_REQUIRED = 426;
    public static final Integer PRECONDITION_REQUIRED = 428;
    public static final Integer TOO_EARLY = 425;
    public static final Integer UNAVAILABLE_FOR_LEGAL_REASONS = 451;
    public static final Integer INTERNAL_SERVER_ERROR = 500;
    public static final Integer NOT_IMPLEMENTED = 501;
    public static final Integer BAD_GATEWAY = 502;
}